

service: template-athena-service

provider:
  name: aws
  runtime: python3.8
  region: us-east-2

functions:
  athena:
    handler: template.template
    role: arn:aws:iam::308967763252:role/service-role/Athena_Triggers-role-3qrg6ygo
    # events:
    #   - schedule: 
    #       rate: cron(0 * * * ? *)
    #       #   cron(MIN HOUR DayMonth Month WeekDay Year)
    #       input: 
    #         stores: ['heritage_15', 'sams_house']
      #- cloudwatchLog: '/aws/lambda/template-athena-service-dev'

  daily:
    handler: daily.handle
    role: arn:aws:iam::308967763252:role/service-role/Athena_Triggers-role-3qrg6ygo
    events:
      - schedule: 
          name: daily-3am
          description: 'Runs daily at 3am'
          rate: cron(0 3 * * ? *) # everyday at 5AM
          input: 
            stores: [heritage_15, heritage_16, sams_house]
        #- cloudwatchLog: '/aws/lambda/template-athena-service-dev-daily'

  weekly:
    handler: weekly.handle
    role: arn:aws:iam::308967763252:role/service-role/Athena_Triggers-role-3qrg6ygo
    events:
      - schedule: 
          name: weekly-sun-4am
          description: 'Runs every Sunday at 4am'
          rate: cron(0 4 ? * SUN *) # every week at 4AM on sunday
          input: 
            stores:
              - heritage_15
              - heritage_16
              - sams_house
        #- cloudwatchLog: '/aws/lambda/template-athena-service-dev-weekly'

  monthly:
    handler: monthly.handle
    role: arn:aws:iam::308967763252:role/service-role/Athena_Triggers-role-3qrg6ygo
    events:
        - schedule: 
          name: monthly-5am
          description: 'Runs on the first day of every month at 5am'
          rate: cron(0 5 1 * ? *) # on the first day of every month at 3AM
          input:
            stores:
              - heritage_15
              - heritage_16
              - sams_house
        #- cloudwatchLog: '/aws/lambda/template-athena-service-dev-monthly'

  campaigns:
    handler: campaigns.handle
    role: arn:aws:iam::308967763252:role/service-role/Athena_Triggers-role-3qrg6ygo
    events:
        - http: 
            path: campaign
            method: GET
            cors: true
        #- cloudwatchLog: '/aws/lambda/template-athena-service-dev-campaigns'


