

service: template-athena-service

provider:
  name: aws
  runtime: python3.8
  region: us-east-2

functions:
  athena:
    handler: template.template
    role: arn:aws:iam::308967763252:role/service-role/Athena_Triggers-role-3qrg6ygo
  daily:
    handler: daily.handle
    role: arn:aws:iam::308967763252:role/service-role/Athena_Triggers-role-3qrg6ygo

